# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([ 3, 6, 32, 7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr = np.array([ 3, 6, 32, 7] , np.int32)

In [5]:
myarr

array([ 3,  6, 32,  7], dtype=int32)

# Array creation : 

## 1.Conversion from other python structures

In [6]:
listarray = np.array([[1,2,3] , [5,8,5] , [0,3,1]])

In [7]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [8]:
listarray.dtype

dtype('int64')

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
np.array({43, 23, 23})

array({43, 23}, dtype=object)

# 2.Intrinsic numpy array creation objects

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
zeros.shape

(2, 5)

In [16]:
zeros.size

10

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1,50,10)

In [20]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
emp_like = np.empty_like(lspace)

In [24]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [27]:
ide.shape

(45, 45)

In [28]:
ide.size

2025

In [29]:
ide.dtype

dtype('float64')

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.reshape(3,33)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

# Numpy Axis

In [44]:
x = [[1,2,3] , [4,5,6] , [7,1,0]]

In [45]:
ar = np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.sum(axis=0)

array([12,  8,  9])

In [48]:
ar.sum(axis=1)

array([ 6, 15,  8])

# Numpy Attributes

In [49]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [50]:
ar.flat

In [51]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim

2

In [54]:
ar.size

9

In [55]:
ar.nbytes

72

In [56]:
one = np.array([1,3,4,634,2])

In [57]:
one.argmax()

np.int64(3)

In [58]:
one.argmin()

np.int64(0)

In [59]:
one.argsort()

array([0, 4, 1, 2, 3])

In [60]:
ar.argmin()

np.int64(8)

In [61]:
ar.argmax()

np.int64(6)

In [63]:
ar.argmax(axis=0)

array([2, 1, 1])

In [64]:
ar.argmin(axis=1)

array([0, 0, 2])

In [65]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [67]:
ar.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [70]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [72]:
ar.sum()

np.int64(29)

In [73]:
ar.max()

np.int64(7)

In [74]:
ar.min()

np.int64(0)

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [76]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [77]:
np.count_nonzero(ar)

8

In [78]:
import sys

In [80]:
py_ar =  [0,4,55,2]

In [81]:
np_ar = np.array(py_ar)

In [83]:
sys.getsizeof(1) * len(py_ar)

112

In [84]:
np_ar.tolist()

[0, 4, 55, 2]